osx_image: xcode8
language: objective-c
install: 
  - bundle install
  - make all
compiler: clang
script:
  - test.sh
matrix:
  include:
    - os: osx
      env:
        BUILD_TARGET=ios
    - os: linux
      env:
        BUILD_TARGET=android
    - os: linux
      env:
        BUILD_TARGET=cpp
