install: 
  - ./install.sh
script:
  - ./test.sh
sudo: false
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8
      env:
        BUILD_TARGET=ios
    - os: linux
      language: android
      env:
        BUILD_TARGET=android
    - os: osx
      language: cpp
      compiler: clang
      env:
        BUILD_TARGET=cpp
