language: objective-c
install: 
  - bundle install
  - make all
script:
  - test.sh
matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        BUILD_TARGET=ios
    - os: linux
      language: android
      env:
        BUILD_TARGET=android
    - os: linux
      compiler: clang
      env:
        BUILD_TARGET=cpp
