install: 
  - ./install.sh
script:
  - ./test.sh
sudo: false
language: cpp
osx_image: xcode8
matrix:
  fast_finish: true
  include:
    - os: osx
      env:
        BUILD_TARGET=ios
    - os: linux
      env:
        BUILD_TARGET=android
        ANDROID_NDK=/home/travis/android-ndk
    - os: osx
      compiler: clang
      env:
        BUILD_TARGET=cpp
