install: 
  - ./install.sh
script:
  - ./test.sh
sudo: false
language: cpp
matrix:
  fast_finish: true
  include:
    - os: osx
      env:
        BUILD_TARGET=ios
    - os: linux
      env:
        BUILD_TARGET=android
    - os: osx
      compiler: clang
      env:
        BUILD_TARGET=cpp
