# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
workspace 'ArgoApp'

target 'ArgoApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArgoApp
  pod 'R.swift'

  target 'ArgoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArgoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
